### ISSUE TITLE
_FPU_EXTENDED and _FPU_DOUBLE not declared...

### ISSUE THREAD

**Issue by OrdinaryMagician** [sneakernets/zdoom#10]
... on line 1942 of d_main.cpp.

These seem to be strictly x86 things so, all that code for setting FPU precision should be removed, or changed to whatever is the ARM equivalent (if any). I'll look into this myself if necessary.

**Comment by sneakernets** [comment]
Is any compiler breaking on this? I'm using GCC 4.8 personally, so it might be ignoring this.

**Comment by OrdinaryMagician** [comment]
Ah, it's gcc 4.9.3

**Comment by sneakernets** [comment]
Fixed in master.
