### ISSUE TITLE
Some sounds are max volume regardless of distance

### ISSUE THREAD

**Issue by sneakernets** [sneakernets/zdoom#11]
As reported on 0.74 release of DemonSteele: Some sounds play at full volume regardless of distance from actor playing the sound. Not sure if it's due to a logic error or the sound format.

The most common is the charge-up sound for the sergeants' blasters.

**Comment by OrdinaryMagician** [comment]
This is an upstream bug in the zdoom openal code, it's being looked into, I think.

**Comment by sneakernets** [comment]
Looks like it's to deal with stereo sounds. I had no idea zdoom had that ability.

**Comment by OrdinaryMagician** [comment]
Yeah, FMOD seems to handle it fine.

**Comment by sneakernets** [comment]
Sounds are converted to Mono before playing. Unfortunate, but a workaround for now. Closing.
